server:
  port: 8888


spring:
  application:
    name: CONFIG-SERVER



eureka:
  client:
    serviceUrl:
      defaultZone: https://ensaregistry-serv.herokuapp.com/eureka
  instance:
    preferIpAddress: true